version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.9.0
        environment:
          MIX_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix do deps.get, compile
      - run: mix test
