aliases:
  ### restore caches
  - &restore_mix_caches
    keys:
      - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - v1-mix-cache-{{ .Branch }}
      - v1-mix-cache

  - &restore_build_caches
    keys:
      - v1-build-cache-{{ .Branch }}
      - v1-build-cache

  ### save caches
  - &save_mix_cache_checksum
    key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
    paths: 'deps'

  - &save_mix_cache_branch
    key: v1-mix-cache-{{ .Branch }}
    paths: 'deps'

  - &save_mix_cache_generic
    key: v1-mix-cache
    paths: 'deps'

  - &save_build_cache_branch
    key: v1-build-cache-{{ .Branch }}
    paths: '_build'

  - &save_build_cache_generic
    key: v1-build-cache
    paths: '_build'

version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.0
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache: *restore_mix_caches
      - restore_cache: *restore_build_caches

      # get deps and compile
      - run: mix deps.get
      - run: mix compile

      - save_cache: *save_mix_cache_checksum
      - save_cache: *save_mix_cache_branch
      - save_cache: *save_mix_cache_generic
      - save_cache: *save_build_cache_generic
      - save_cache: *save_build_cache_branch

  test:
    docker:
      - image: circleci/elixir:1.9.0

    steps:
      - checkout
      - restore_cache: *restore_mix_caches
      - restore_cache: *restore_build_caches

      # run test coverage
      - run: mix coveralls.html

      - store_artifacts:
          path: cover
          destination: coverage_results

  docs:
    docker:
      - image: circleci/elixir:1.9.0
        environment:
          MIX_ENV: test

    steps:
      - checkout
      - restore_cache: *restore_mix_caches
      - restore_cache: *restore_build_caches

      # generate docs
      - run: mix docs

      - store_artifacts:
          path: docs
          destination: documentation

  typespecs:
    docker:
      - image: circleci/elixir:1.9.0
        environment:
          MIX_ENV: test

    steps:
      - checkout
      - restore_cache: *restore_mix_caches
      - restore_cache: *restore_build_caches

      # run typespecs
      - run: mix dialyzer --halt-exit-status

  format:
    docker:
      - image: circleci/elixir:1.9.0
        environment:
          MIX_ENV: test

    steps:
      - checkout

      # check formatting
      - run: mix format --check-formatted

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - format:
          requires:
            - build
      - docs:
          requires:
            - build
      - typespecs:
          requires:
            - build
      - test:
          requires:
            - build
